import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Layout from "~/components/layout";

export default function Home() {
  //To add a pose
  // const {mutate: addPose} = api.pose.addPose.useMutation();

  //To add a pose
  // const addOnePose = (nameParam: string, landmarksParam: number[], poseNumParam: number) => {
  //   addPose({name: nameParam, landmarks: landmarksParam, poseNum: poseNumParam});
  // }

  const PlayGameButton = () => {
    return (
      <div className="flex justify-center w-full">
        <Link 
          href="/play"
          className="bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"
        >Start posing!</Link>
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Pose Master</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/frontPose.png" />
      </Head>
      <Layout>
      <main className="relative">
        <div className="h-screen flex justify-center items-center">
          <div id="phone-case" className="relative mx-auto border-gray-800 bg-gray-800 border-[14px] rounded-[2.5rem] h-[720px] w-[414px]">
              <div className="absolute top-10 w-full flex flex-col justify-center items-center gap-2">
                <h1 className="text-7xl font-extrabold">POSERS</h1>
                <h3 className="text-lg">Created by Alastair Deng</h3>
              </div>
              <div className="absolute w-full top-1/3 flex justify-center items-center">
                <Image src="/frontPose.png" width={250} height={250} alt="" />
              </div>
              <div className="absolute w-full bottom-10">
                <PlayGameButton />
              </div>
          </div>
        </div>
        <InfoBlurb />
      </main>
      </Layout>
    </>
  );
}

export const InfoBlurb = () => {
  return (
    <div className="absolute left-full top-0 hidden lg:flex lg:justify-center lg:items-center h-full w-full p-6">
      <ul className="flex flex-col gap-4">
        <li>
          Don't know how to play? Check out <Link href="/how-to-play" className="text-blue-500 hover:underline">this</Link> page.
        </li>
        <li>
          Posers! is being made into an IOS app! Follow Alastair Deng 
          on <Link href="https://github.com/adeng27" className="text-blue-500 hover:underline" target="_blank">Github</Link> for more info.
        </li>
        <li>
          Send feedback and questions to <span className="hover:underline text-blue-500">adeng27@stanford.edu</span>.
        </li>
      </ul>
    </div>
  )
}
